# Generated by Django 4.0.5 on 2022-06-19 14:07

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MemoryPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('comment', models.TextField(max_length=500)),
                ('long', models.DecimalField(decimal_places=17, max_digits=20, null=True)),
                ('lat', models.DecimalField(decimal_places=17, max_digits=20, null=True)),
                ('created_at', models.DateTimeField(default=datetime.datetime(2022, 6, 19, 14, 7, 18, 57835))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
